<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */
?>
<div x-data="initFixedProductTaxTotalSegment">
<template x-if="isFptSegment">
    <div :class="wrapperClass">
        <div x-html="formatTotalLabel"></div>
        <div x-text="formatFptTotal" class="justify-self-end"></div>
    </div>
</template>
</div>
