<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\GraphqlViewModel\ViewModel\GraphqlViewModel;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Cart\Items;
use Hyva\Theme\ViewModel\Currency;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\Slider;
use Hyva\Theme\ViewModel\Store;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Store $viewModelStore */
$viewModelStore = $viewModels->require(Store::class);

/** @var Wishlist $wishlistViewModel */
$wishlistViewModel = $viewModels->require(Wishlist::class);

/** @var ProductCompare $compareViewModel */
$compareViewModel = $viewModels->require(ProductCompare::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var GraphqlViewModel $gqlViewModel */
$gqlViewModel = $viewModels->require(GraphqlViewModel::class);

/** @var Slider $sliderViewModel */
$sliderViewModel = $viewModels->require(Slider::class);

/** @var Currency $currencyViewModel */
$currencyViewModel = $viewModels->require(Currency::class);
$currencySymbol = $currencyViewModel->getCurrentCurrencySymbol();

$uniqueId = '_' . uniqid();
$query = $block->getGraphqlQuery();
/**
 * Can be a custom filter, like  "color: { in: [\"yellow\",\"orange\"] },"
 * @var string $productFilters
 */
$productFilters = $block->getProductFilters();
$categoryIds = $block->getCategoryIds();
$priceFrom = $block->getPriceFrom();
$priceTo = $block->getPriceTo();
$pageSize = $block->getPageSize() ?: '8';
$sortAttribute = $block->getSortAttribute() ?: 'position';
$sortDirection = $block->getSortDirection() ?: 'ASC';
$title = $block->getTitle();
$type = $block->getType() ?: "";

$isLinkedProduct = (in_array($type, ['related', 'crosssell', 'upsell']));

if ($isLinkedProduct) {
    if ($type === 'crosssell') {
        /** @var Items $cartItemsViewModel */
        $cartItemsViewModel = $viewModels->require(Items::class);
        $productSkus = $cartItemsViewModel->getCartItemsSkus();
    } elseif ($product = $block->getProduct()) {
        $productSkus = $block->getProduct()->getSku();
    } else {
        $productSkus = '';
    }
} else {
    $productSkus = $block->getProductSkus();
}

$productSkuFilter = $productSkus ?
    sprintf("sku: { in: [\"%s\"] },", join("\",\"", explode(',', $productSkus))) :
    "";

$categoryFilter = $categoryIds ?
    sprintf("category_id: { in: [\"%s\"] }", join("\",\"", explode(',', $categoryIds))) :
    "";
$priceFilter = $priceFrom || $priceTo ? "price: { from: \"$priceFrom\", to: \"$priceTo\" }," : "";

$productAttributes = "
      sku
      id
      name
      small_image {
        label
        url
      }
      url_key
      url_suffix
      visibility
      status
      price_range {
        minimum_price {
          regular_price {
            value
            currency
          }
          final_price {
            value
            currency
          }
        }
      }";

$items = $isLinkedProduct ?
    "{$type}_products {
        $productAttributes
    }" :
    $productAttributes;

$graphqlQuery = $gqlViewModel->query("slider_products_query", $query ?: "
{
  products(
    filter: {
      $productFilters
      $productSkuFilter
      $categoryFilter
      $priceFilter
      }
    pageSize: {$pageSize},
    sort: {{$sortAttribute}: {$sortDirection}}
    ) {
    items {
        $items
    }
  }
}", ['is_linked_product' => $isLinkedProduct, 'type' => $type]);

$queryResponseDataCallback = ! $isLinkedProduct
    ? "
                            (data, component) => {
                                component.currency = (data &&
                                    data.data &&
                                    data.data.currency);
                                return data &&
                                    data.data &&
                                    data.data.products &&
                                    data.data.products.items;
                            }"
    : "
                            (data, component) => {
                                component.currency = (data &&
                                    data.data &&
                                    data.data.currency);
                                return data &&
                                    data.data &&
                                    data.data.products &&
                                    data.data.products.items &&
                                    data.data.products.items[0] &&
                                    data.data.products.items[0]['{$escaper->escapeJs($type)}_products'] &&
                                    // only use products with visibility set to `Catalog` or `Catalog, Search` (2 or 4)
                                    // with status set to '1' (enabled)
                                    data.data.products.items[0]['{$escaper->escapeJs($type)}_products']
                                        .filter(product => {
                                            return (
                                                [2,4].includes(product.visibility) &&
                                                product.status.toString() === '1'
                                            )
                                        }) || []

                            }";

$sliderItemTemplate = 'Magento_Catalog::product/slider-item.phtml';

echo $sliderViewModel->getSliderForQuery($sliderItemTemplate, $graphqlQuery, $queryResponseDataCallback)
    ->setTitle($title)
    ->toHtml();
