<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\Store;
use Hyva\Theme\ViewModel\Wishlist;
use Hyva\Theme\ViewModel\ProductPage;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $viewModelProducts */
$viewModelProducts = $viewModels->require(ProductPage::class);

/** @var Store $viewModelStore */
$viewModelStore = $viewModels->require(Store::class);

/** @var Wishlist $wishlistViewModel */
$wishlistViewModel = $viewModels->require(Wishlist::class);

/** @var ProductCompare $compareViewModel */
$compareViewModel = $viewModels->require(ProductCompare::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$uniqueId = '_' . uniqid();
$title = __('Recently Viewed Products');


$widgetAttributesToShow = explode(',', $block->getData('show_attributes'));
$widgetButtonsToShow = explode(',', $block->getData('show_buttons'));
$currentProductSku = $viewModelProducts->getProduct() ? $viewModelProducts->getProduct()->getSku() : 'false';
?>
    <script>

        function initSliderComponent<?= /** @noEscape */$uniqueId ?>() {

            const refreshLocalStorageData = function(){
                /***
                * Remove expired products in the local storage
                ***/
                if(localStorage.getItem('recently_viewed_skus')){

                    let updatedlocalStorageData = '';
                    const recentlyViewedSkusArray = localStorage.getItem('recently_viewed_skus').split(",");

                    recentlyViewedSkusArray.forEach(function myFunction(skuData,key){
                        // split each product's sku and expiry data
                        const tempSplitArray  = skuData.split(" ");
                        if(tempSplitArray[1] > Date.now()){
                            updatedlocalStorageData +=  ',' + tempSplitArray[0] + ' ' + tempSplitArray[1];
                        }
                    });
                    updatedlocalStorageData = updatedlocalStorageData.replace(/[,]/, '');
                    localStorage.removeItem('recently_viewed_skus');
                    localStorage.setItem('recently_viewed_skus', updatedlocalStorageData);
                }
            }
            const putDataInLocalStorage = function(data){

                const localStorageDataToPut = data['current_product_sku'] + ' ' + data['expiry'];
                if(!localStorage.getItem('recently_viewed_skus')){
                    localStorage.setItem('recently_viewed_skus', localStorageDataToPut);
                }else{
                    // Remove expired products in the local storage
                    refreshLocalStorageData();
                    // Avoid adding sku already in the storage
                    const recentlyViewedSkusArray = localStorage.getItem('recently_viewed_skus').split(",");
                    let skuAlreadyInList = false;

                    recentlyViewedSkusArray.forEach(function myFunction(skuData,key){
                        // split each product's sku and expiry data
                        let tempSplitArray  = skuData.split(" ");
                        if(tempSplitArray[0] == data['current_product_sku']){
                            skuAlreadyInList = true;
                        }
                    });

                    // Avoid adding sku already in the storage
                    if(!skuAlreadyInList){
                        // if sku not already in list, append current product's data in the list
                        localStorage.setItem('recently_viewed_skus', localStorageDataToPut + ',' + localStorage.getItem('recently_viewed_skus'));
                    }
                }
            }
            const createLocalStorageData = function(){
                // get current product sku and calculate its expiry from local storage
                const currentProductData = [];
                currentProductData['current_product_sku'] = '<?= $escaper->escapeJs($currentProductSku) ?>';
                let lifeTimeOfProducts = <?= (int) $viewModelProducts->getRecentlyViewedLifeTime() ?>;
                lifeTimeOfProducts = lifeTimeOfProducts * 1000;
                currentProductData['expiry'] = Date.now() + lifeTimeOfProducts;
                return currentProductData;
            }

            const currentProductSku = '<?= $escaper->escapeJs($currentProductSku) ?>';
            if(currentProductSku !== 'false'){
                // Recently Viewed Products' data adding into the local storage
                putDataInLocalStorage(createLocalStorageData());
            }else{
                // Remove expired products in the local storage
                refreshLocalStorageData();
            }

            return {
                active: 0,
                products: [],
                currency: [],
                currentProductSku: '<?= $escaper->escapeJs($currentProductSku) ?>',
                noOfProductsToShow: <?= (int) $block->getData('page_size') ?>,
                loading: true,
                minHeight() {
                    return 'min-height: ' + ((this.loading && '491px') || 0);
                },
                query: '',
                getProducts($nextTick) {
                    let itemsToFetch = [];
                    if(localStorage.getItem('recently_viewed_skus')){
                        /* Fetching Products from local storage */
                        const recentlyViewedSkusArray = localStorage.getItem('recently_viewed_skus').split(",");

                        /* avoid showing the current product */
                        itemsToFetch = recentlyViewedSkusArray
                            .map(skuData => skuData.split(" ")[0])
                            .filter(sku => sku !== this.currentProductSku);
                    }

                    if(!itemsToFetch.length){
                        this.noOfProductsToShow = 0;
                    }else{
                        itemsToFetch = itemsToFetch.slice(0, this.noOfProductsToShow);
                    }

                    this.query = `{
                        products(
                            filter: {
                                sku: { in: ${JSON.stringify(itemsToFetch)} },
                            }
                            pageSize: ${this.noOfProductsToShow},
                        ) {
                            items {
                                sku
                                id
                                name
                                small_image {
                                    label
                                    url
                                }
                                url_key
                                url_suffix
                                visibility
                                status
                                price_range {
                                        minimum_price {
                                        regular_price {
                                            value
                                            currency
                                        }
                                        final_price {
                                            value
                                            currency
                                        }
                                    }
                                }
                            }
                        }
                    }`;

                    window.fetch('/graphql?' + new URLSearchParams({query: this.query}), {
                        method: 'GET',
                        headers: {
                            'Store': '<?= /* @noEscape */ $viewModelStore->getStoreCode() ?>'
                        },
                    })
                        .then((response) =>  response.json())
                        .then((result) => {
                                this.currency = (result &&
                                result.data &&
                                result.data.currency);

                                    const responseProducts = (
                                        result &&
                                        result.data &&
                                        result.data.products &&
                                        result.data.products.items
                                    ) || [];

                                    // fix sorting of the response-products according to the sorting of the requested-products
                                    const sortedProducts = [];

                                    itemsToFetch.forEach(function myFunction(sku,key){
                                        responseProducts.forEach(function myFunction(productData,index){
                                            if(sku === productData.sku){
                                                sortedProducts[key] = productData;
                                            }
                                        });
                                    });
                                    return this.products = sortedProducts;
                            }
                        ).finally(() => {
                            this.loading = false
                            $nextTick(() => this.calcPageSize());
                        });
                },
                addToWishlist(productId) {
                    const formKey = hyva.getFormKey();
                    const postUrl = BASE_URL+"wishlist/index/add/";
                    fetch(postUrl, {
                        "headers": {
                            "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                        },
                        "body": new URLSearchParams({form_key: hyva.getFormKey(), product: productId, uenc: btoa(window.location.href)}),
                        "method": "POST",
                        "mode": "cors",
                        "credentials": "include"
                    }).then(function (response) {
                        if (response.redirected) {
                            window.location.href = response.url;
                        } else if (response.ok) {
                            return response.json();
                        } else {
                            typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                                [{
                                    type: "warning",
                                    text: "<?= $escaper->escapeHtml(__('Could not add item to wishlist.')) ?>"
                                }], 5000
                            );
                        }
                    }).then(function (response) {
                        if(!response) { return }
                        typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                            [{
                                type: (response.success) ? "success" : "error",
                                text: (response.success)
                                    ? "<?= $escaper->escapeHtml(
                                        __("%1 has been added to your Wish List.", __("Product"))
                                    ) ?>" : response.error_message
                            }], 5000
                        );
                        const reloadCustomerDataEvent = new CustomEvent("reload-customer-section-data");
                        window.dispatchEvent(reloadCustomerDataEvent);
                    }).catch(function (error) {
                        typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                            [{
                                type: "error",
                                text: error
                            }], 5000
                        );
                    });
                },
                addToCompare(productId) {
                    const formKey = hyva.getFormKey();
                    const postUrl = BASE_URL + 'catalog/product_compare/add/';

                    fetch(postUrl, {
                        "headers": {
                            "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                        },
                        "body": new URLSearchParams({form_key: hyva.getFormKey(), product: productId, uenc: btoa(window.location.href)}),
                        "method": "POST",
                        "mode": "cors",
                        "credentials": "include"
                    }).then(function (response) {
                        if (response.redirected) {
                            window.location.href = response.url;
                        }
                    }).catch(function (error) {
                        typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                            [{
                                type: "error",
                                text: error
                            }], 5000
                        );
                    });
                },
                getSlider() {
                    return this.$el.querySelector('.js_slides');
                },
                pageSize: 1,
                pageFillers: 0,
                calcPageSize() {
                    const slider = this.getSlider();
                    if (slider) {
                        this.pageSize = Math.round(slider.clientWidth / slider.querySelector('.js_slide').clientWidth);
                        this.pageFillers = (
                            this.pageSize * Math.ceil(this.products.length / this.pageSize)
                        ) - this.products.length;
                    }
                },
                calcActive(event) {
                    const slider = this.getSlider();
                    if (slider) {
                        this.active = Math.ceil(
                            Math.round(
                                slider.scrollLeft / (slider.scrollWidth / this.products.length)
                            ) / this.pageSize
                        ) * this.pageSize;
                    }
                }
            }
        }

    </script>



    <section class="my-12 text-gray-700 body-font"
            x-data="initSliderComponent<?= /** @noEscape */ $uniqueId?>()"
            x-init="getProducts($nextTick);"
            :style="minHeight()"
            @resize.window.debounce="calcPageSize(); $nextTick( function() { calcActive() })"
    >
        <template x-if="products && products.length">
            <div class="container relative px-5">
                    <div class="container flex flex-col items-center pt-6 pb-3 mx-auto mb-6 border-b-2
                        border-gray-300 md:flex-row">
                        <h3 class="text-2xl font-medium text-gray-900 title-font">
                            <?= $escaper->escapeHtml($title); ?>
                        </h3>
                    </div>
                <div class="relative w-full overflow-x-hidden">
                    <div class="relative flex flex-nowrap w-full overflow-auto transition-all js_slides snap"
                        @scroll.debounce="calcActive"
                    >
                        <template x-for="product in products">
                            <div class="flex-none w-full py-1 js_slide md:w-1/2 lg:w-1/3 xl:w-1/4">
                                <div class="mx-1 card card-interactive">
                                    <?php if(in_array("image", $widgetAttributesToShow)): ?>
                                        <a :href="'<?= $escaper->escapeJs($escaper->escapeUrl($block->getBaseUrl())) ?>' +
                                            product.url_key + (product.url_suffix || '')"
                                        class="relative flex items-center bg-white product photo product-item-photo"
                                        style="padding-top:100%"
                                        tabindex="-1">
                                            <span class="absolute top-0 left-0 flex flex-wrap content-center w-full h-full p-2
                                                overflow-hidden align-center hover:shadow-sm">
                                                <img class="self-center w-full h-auto"
                                                    :src="product.small_image.url"
                                                    :alt="product.small_image.label"
                                                    loading="lazy"
                                                    width="500"
                                                    height="500"
                                                />
                                            </span>
                                        </a>
                                    <?php endif; ?>
                                    <?php if(in_array("name", $widgetAttributesToShow)): ?>
                                        <p class="flex items-center justify-center px-1 pt-3 text-primary">
                                            <a class="truncate product-item-link"
                                            :href="'<?= $escaper->escapeJs($escaper->escapeUrl($block->getBaseUrl())) ?>' +
                                                    product.url_key + (product.url_suffix || '')"
                                            >
                                                <span x-html="product.name"></span>
                                            </a>
                                        </p>
                                    <?php endif; ?>
                                    <?php if(in_array("price", $widgetAttributesToShow)): ?>
                                        <p class="pt-1 text-lg text-center text-gray-900"
                                        x-text="hyva.formatPrice(product.price_range.minimum_price.final_price.value)"></p>
                                    <?php endif; ?>
                                        <p class="flex flex-wrap gap-2 inline p-3">
                                            <?php if(in_array("learn_more", $widgetAttributesToShow)): ?>
                                                <a class="justify-center w-auto mr-auto btn btn-primary"
                                                :href="'<?= $escaper->escapeJs($escaper->escapeUrl($block->getBaseUrl())) ?>' +
                                                        product.url_key + (product.url_suffix || '')">
                                                    <span class="inline"><?= $escaper->escapeHtml(__('View Product')) ?></span>
                                                </a>
                                            <?php endif; ?>
                                            <span class="inline-flex gap-2">
                                                <?php if (in_array("add_to_compare", $widgetButtonsToShow)): ?>
                                                    <?php if ($compareViewModel->showInProductList()): ?>
                                                        <button @click.prevent="addToCompare(product.id)"
                                                                aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>"
                                                                class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex
                                                                items-center justify-center text-gray-500 hover:text-yellow-500"
                                                        >
                                                        <?= $heroicons->scaleHtml("w-5 h-5") ?>
                                                    </button>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                                <?php if (in_array("add_to_wishlist", $widgetButtonsToShow)): ?>
                                                    <?php if ($wishlistViewModel->isEnabled()): ?>
                                                        <button
                                                            aria-label="<?= $escaper->escapeHtml(__('Add to Wish List')) ?>"
                                                            @click.prevent="addToWishlist(product.id)"
                                                            class="inline-flex items-center justify-center w-10 h-10 p-0 ml-auto
                                                        text-gray-500 bg-gray-200 border-0 rounded-full hover:text-red-600"
                                                        >
                                                        <?= $heroicons->heartHtml("w-5 h-5", 25, 25) ?>
                                                    </button>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </span>
                                        </p>
                                </div>
                            </div>
                        </template>
                        <div :class="{
                            'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex-none py-1' : pageFillers > 0
                            }"></div>
                        <div :class="{
                            'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex-none py-1' : pageFillers > 1
                            }"></div>
                        <div :class="{
                            'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex-none py-1' : pageFillers > 2
                            }"></div>
                    </div>
                </div>
                <template x-if="products.length && products.length > pageSize">
                    <div class="flex items-center justify-center flex-1 p-4" x-cloak>
                        <button
                            aria-label="<?= $escaper->escapeHtmlAttr(__('Previous')) ?>"
                            class="w-8 h-8 mx-4 text-black rounded-full outline-none focus:outline-none"
                            :class="{ 'invisible' : active === 0 }"
                            @click="getSlider().scrollLeft =
                                (getSlider().scrollWidth / products.length) * (active-pageSize); active=active-pageSize;">
                            <?= $heroicons->chevronLeftHtml("w-5 h-5", 25, 25) ?>
                        </button>
                        <template x-for="(product, index) in products" :key="index">
                            <span class="flex-shrink-0 block w-3 h-3 mx-1 bg-black bg-opacity-25 rounded-full shadow cursor-pointer"
                                :class="{
                                        'bg-opacity-100': active === index,
                                        'hidden': (pageSize !== 1 && !!(index % pageSize))
                                        }"
                                @click="getSlider().scrollLeft =
                                        (getSlider().scrollWidth / products.length) * index; active=index;">
                            </span>
                        </template>
                        <button
                            aria-label="<?= $escaper->escapeHtmlAttr(__('Next')) ?>"
                            class="w-8 h-8 mx-4 text-black rounded-full outline-none focus:outline-none"
                            :class="{ 'invisible' : active >= products.length-pageSize }"
                            @click="getSlider().scrollLeft =
                                (getSlider().scrollWidth / products.length) * (active+pageSize); active=active+pageSize">
                            <?= $heroicons->chevronRightHtml("w-5 h-5", 25, 25) ?>
                        </button>
                    </div>
                </template>
            </div>
        </template>
    </section>
