<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */
?>
<div x-data="initDiscountTotalSegment">
<template x-if="isDiscountSegment" data-total-code="discount">
    <div :class="wrapperClass">
        <div x-text="formatTotalLabel"></div>
        <div x-text="formatDiscountValue" class="justify-self-end"></div>
    </div>
</template>
</div>
