<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */
?>
<div x-data="initShippingTotalSegment">
<!-- display shipping including and excluding tax -->
<template x-if="isShippingSegmentAndDisplayBoth">
    <div :class="wrapperClass">
        <div x-text="formatTotalLabelExclTax"></div>
        <div :data-amount="formatShippingAmount" class="justify-self-end"></div>
        <div x-text="formatTotalLabelInclTax"></div>
        <div x-text="formatShippingInclTax" class="justify-self-end"></div>>
    </div>
</template>

<!-- display shipping excluding tax -->
<template x-if="isShippingSegmentAndDisplayExcl">
    <div :class="wrapperClass">
        <div x-text="formatTotalLabel"></div>
        <div x-text="formatShippingTotalValue" class="justify-self-end"></div>
    </div>
</template>

<!-- display shipping including tax -->
<template x-if="isShippingSegmentAndDisplayIncl">
    <div :class="wrapperClass">
        <div x-text="formatTotalLabel"></div>
        <div x-text="formatShippingInclTax" class="justify-self-end"></div>
    </div>
</template>
</div>
