<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */
?>
<div x-data="initGrandTotalSegment">
<template x-if="isGrandTotal">
    <div :class="wrapperClassTotals">
        <div x-text="formatTotalLabel"></div>
        <div x-text="formatGrandTotal" class="justify-self-end"></div>
    </div>
</template>
</div>
