<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */
?>
<template x-if="isShippingTotal">
    <div :class="wrapperClass">>
        <div x-text="formatTotalLabel"></div>
        <div x-text="formatShippingTotal" class="justify-self-end"></div>
    </div>
</template>
