<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */
?>
<div x-data="initSubtotalSegment">
<template x-if="isSubtotal">
    <div :class="wrapperClass">
        <div x-text="segment.title"></div>
        <div x-text="hyva.formatSubtotal" class="justify-self-end"></div>
    </div>
</template>
</div>
