<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SwatchRenderer;
use Magento\Framework\Escaper;
use Magento\Swatches\Block\Product\Renderer\Configurable;
use Magento\Swatches\ViewModel\Product\Renderer\Configurable as ConfigurableViewModel;

/** @var Configurable $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */

/** @var ConfigurableViewModel $configurableViewModel */
$configurableViewModel = $viewModels->require(ConfigurableViewModel::class);

/** @var SwatchRenderer $swatchRendererViewModel */
$swatchRendererViewModel = $viewModels->require(SwatchRenderer::class);

$product = $block->getProduct();
$productId = $product->getId();

$attributes = $block->decorateArray($block->getAllowAttributes());

$layout = $block->getLayout();
$swatchItemBlock = $layout->getBlock('product.swatch.item');
$swatchItemBlock->setData('product_id', $productId);

$jsonConfig = $block->getJsonConfig();
$jsonSwatchConfig = $block->getJsonSwatchConfig();
$swatchConfig = json_decode($jsonSwatchConfig, true);
?>
<?php if ($product->isSaleable() && count($attributes)): ?>
    <script>
        function initConfigurableSwatchOptions() {
            return Object.assign(
                initConfigurableOptions('<?= (int) $productId ?>', <?= /* @noEscape */ $jsonConfig ?>),
                initSwatchOptions(<?= /* @noEscape */ $jsonSwatchConfig ?>),
                {
                    reflectOption(event) {
                        this.changeOption(event.target.dataset.attributeId, event.target.value);
                    }
                }
            );
        }
    </script>
    <?php $hyvaCsp->registerInlineScript() ?>

    <div
        x-data="initConfigurableSwatchOptions()"
        class="mb-2 relative"
    >
        <h2 class="mb-4 text-xl font-medium text-gray-900 title-font">
            <?= $escaper->escapeHtml(__('Product Options:')) ?>
        </h2>
        <?php foreach ($attributes as $attribute): ?>
            <?php
                $attributeId = $attribute->getAttributeId();
                $productAttribute = $attribute->getProductAttribute();

                $isSwatch = $swatchRendererViewModel->isSwatchAttribute($productAttribute);
                $productOptions = $attribute->getOptions();
                $attributeSwatchConfig = $swatchConfig[$attributeId] ?? [];
            ?>
            <?php if ($isSwatch): ?>
                <fieldset class="mt-4">
                    <div class="grid sm:grid-cols-2 gap-2 items-center">
                        <legend class="mb-0 text-base font-medium"><?= $escaper->escapeHtml($productAttribute->getStoreLabel()) ?></legend>
                        <div class="flex flex-wrap gap-2">
                            <?php foreach ($productOptions ?? [] as $option): ?>
                                <?= /* @noEscape */ $swatchItemBlock
                                    ->setData('option', $option)
                                    ->setData('swatch_data', $attributeSwatchConfig[$option['value_index']] ?? null)
                                    ->setData('attribute_id', $attributeId)
                                    ->toHtml(); ?>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </fieldset>
            <?php else: ?>
                <div role="group" class="grid sm:grid-cols-2 gap-2 items-center mt-4">
                    <label class="mb-0 text-base font-medium" for="attribute<?= $escaper->escapeHtmlAttr($attributeId) ?>">
                        <?= $escaper->escapeHtml($productAttribute->getStoreLabel()) ?>
                    </label>
                    <select
                        name="super_attribute[<?= $escaper->escapeHtmlAttr($attributeId) ?>]"
                        id="attribute<?= $escaper->escapeHtmlAttr($attributeId) ?>"
                        data-attribute-id="<?= $escaper->escapeHtmlAttr($attributeId) ?>"
                        @change="reflectOption"
                        required
                    >
                        <option value=""><?= $escaper->escapeHtml(__('Choose an Option...')) ?></option>
                        <?php foreach ($productOptions ?? [] as $option): ?>
                            <option value="<?= $escaper->escapeHtmlAttr($option['value_index']) ?>">
                                <?= $escaper->escapeHtml($option['store_label']) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
        <?php if ($configurableViewModel->getShowSwatchTooltip()): ?>
            <?= /* @noEscape */ $block->getBlockHtml('product.swatch.tooltip') ?>
        <?php endif; ?>
    </div>
<?php endif; ?>
