<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

$order = $block->getOrder() ?>
<div class="actions-toolbar">
    <a href="<?= $block->escapeUrl($block->getPrintAllCreditmemosUrl($order)) ?>"
       class="btn btn-secondary"
       target="_blank"
       rel="noopener">
        <svg class="mr-1 inline-block" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
             stroke="currentColor" width="24" height="24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/>
        </svg>
        <span><?= $block->escapeHtml(__('Print All Refunds')) ?></span>
    </a>
</div>
<?php foreach ($order->getCreditmemosCollection() as $creditmemo) : ?>
    <div class="order-title">
        <strong><?= $block->escapeHtml(__('Refund #')) ?><?= $block->escapeHtml(
                $creditmemo->getIncrementId()
            ) ?> </strong>
        <a href="<?= $block->escapeUrl($block->getPrintCreditmemoUrl($creditmemo)) ?>"
           class="text-primary underline"
           target="_blank"
           rel="noopener">
            <span><?= $block->escapeHtml(__('Print Refund')) ?></span>
        </a>
    </div>

    <?= $block->getCommentsHtml($creditmemo) ?>

    <div class="order-items creditmemo">
        <div class="hidden lg:grid grid-cols-7 text-sm text-secondary ">
            <div class="p-2 col-span-2"><?= $escaper->escapeHtml(__('Product Name')) ?></div>
            <div class="p-2"><?= $escaper->escapeHtml(__('Price')) ?></div>
            <div class="p-2"><?= $escaper->escapeHtml(__('Qty')) ?></div>
            <div class="p-2 text-right"><?= $escaper->escapeHtml(__('Subtotal')) ?></div>
            <div class="p-2 text-right"><?= $block->escapeHtml(__('Discount Amount')) ?></div>
            <div class="p-2 text-right"><?= $block->escapeHtml(__('Row Total')) ?></div>
        </div>
        <?php $items = $creditmemo->getAllItems(); ?>
        <?php foreach ($items as $item) : ?>
            <?php if (!$item->getOrderItem()->getParentItem()) : ?>
                <?= $block->getItemHtml($item) ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <div class="flex justify-end border-t border-container">
            <div class="lg:w-1/3">
                <div class="grid grid-cols-2 text-right p-2 gap-2">
                    <?= $block->getTotalsHtml($creditmemo) ?>
                </div>
            </div>
        </div>
    </div>
<?php endforeach; ?>
