<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/**
 * @var $block \Magento\Sales\Block\Order\Comments
 * @see \Magento\Sales\Block\Order\Comments
 */
?>
<?php if ($block->hasComments()) : ?>
    <div class="order additional details comments my-3">
        <div><strong><?= $block->escapeHtml($block->getTitle()) ?></strong></div>
        <?php foreach ($block->getComments() as $commentItem) : ?>
            <div class="flex justify-between">
                <span class="inline-block w-3/12">
                    <?= /* @noEscape */
                    $block->formatDate($commentItem->getCreatedAt(), \IntlDateFormatter::MEDIUM, true) ?>
            </span>
                <span class="inline-block w-8/12"><?= $block->escapeHtml($commentItem->getComment()) ?></span>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
