<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/**
 * @var $block \Magento\Sales\Block\Order\Info
 * @var \Magento\Framework\Escaper $escaper
 */ ?>
<?php $order = $block->getOrder() ?>
<div class="block block-order-details-view">
    <div class="mb-4 text-lg"><?= $escaper->escapeHtml(__('Order Information')) ?></div>
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-2">
        <?php if (!$order->getIsVirtual()) : ?>
            <div class="w-full py-4">
                <p class="font-semibold mb-2"><?= $escaper->escapeHtml(__('Shipping Address')) ?></p>
                <div class="box-content">
                    <address><?= /* @noEscape */
                        $block->getFormattedAddress($order->getShippingAddress()) ?></address>
                </div>
            </div>
            <div class="w-full py-4">
                <p class="font-semibold mb-2"><?= $escaper->escapeHtml(__('Shipping Method')) ?></p>
                <div class="box-content">
                    <?php if ($order->getShippingDescription()) : ?>
                        <?= $escaper->escapeHtml($order->getShippingDescription()) ?>
                    <?php else : ?>
                        <?= $escaper->escapeHtml(__('No shipping information available')) ?>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>
        <div class="w-full py-4">
            <p class="font-semibold mb-2"><?= $escaper->escapeHtml(__('Billing Address')) ?></p>
            <div class="box-content">
                <address><?= /* @noEscape */
                    $block->getFormattedAddress($order->getBillingAddress()) ?></address>
            </div>
        </div>
        <div class="w-full py-4">
            <p class="font-semibold mb-2"><?= $escaper->escapeHtml(__('Payment Method')) ?></p>
            <div class="box-content">
                <?= $block->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>
