<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/** @var  $block \Magento\Sales\Block\Order\View */ ?>

<?php $history = $block->getOrder()->getVisibleStatusHistory() ?>
<?php if (!empty($history)) : ?>
    <div class="my-3">
        <div><strong><?= $block->escapeHtml(__('About Your Order')) ?></strong></div>
        <?php foreach ($history as $historyItem) : ?>
            <div class="flex justify-between">
                <span class="inline-block w-3/12">
                    <?= /* @noEscape */
                    $block->formatDate($historyItem->getCreatedAt(), \IntlDateFormatter::MEDIUM, true) ?>
                </span>
                <span class="inline-block w-8/12"><?= $block->escapeHtml($historyItem->getComment()) ?></span>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
