<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var StoreConfig $storeConfig */

$storeConfig = $viewModels->require(StoreConfig::class);
$siteKeyV2 = $storeConfig->getStoreConfig('recaptcha_frontend/type_invisible/public_key');
?>
<?php if ($siteKeyV2): ?>
    <div class="g-recaptcha"
         data-sitekey="<?= $escaper->escapeJs($siteKeyV2) ?>">
    </div>
<?php else: ?>
    <div class="control">
        <input type="hidden"
               value=""
               class="form-input"
               name="g-recaptcha-response"
        />
    </div>
<?php endif; ?>
