<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Swatches\Model\Swatch;
use Magento\Swatches\ViewModel\Product\Renderer\Configurable as ConfigurableViewModel;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ConfigurableViewModel $configurableViewModel */
$configurableViewModel = $viewModels->require(ConfigurableViewModel::class);

$productId = $block->getProductId();
$attributeId = $block->getAttributeId();
$option = $block->getOption();

if (!$productId || !$attributeId || !$option) {
    return '';
}

$optionId = $option['value_index'];
$optionLabel = $option['store_label'];
$id = "attribute-option" . $productId . "-" . $optionId;
$swatchData = $block->getSwatchData();
$swatchType = (int) ($swatchData['type'] ?? Swatch::SWATCH_TYPE_TEXTUAL);
$isVisual = in_array($swatchType, [Swatch::SWATCH_TYPE_VISUAL_COLOR, Swatch::SWATCH_TYPE_VISUAL_IMAGE], true);
$toolTipData = [
    'preview' => $swatchData['thumb'] ?? $swatchData['value'],
    'label' => $optionLabel,
    'type' => $swatchType === Swatch::SWATCH_TYPE_VISUAL_COLOR ? 'color' : ($swatchType === Swatch::SWATCH_TYPE_VISUAL_IMAGE ? 'image' : 'text'),
];
?>
<label
    for="<?= $escaper->escapeHtmlAttr($id) ?>"
    class="form-swatch my-0"
    data-swatch-type="<?= $escaper->escapeHtmlAttr($isVisual ? 'visual' : 'text') ?>"
    data-attribute-id="<?= (int) $attributeId ?>"
    data-option-id="<?= $escaper->escapeHtmlAttr($optionId) ?>"
    <?php if ($configurableViewModel->getShowSwatchTooltip()): ?>
        @mouseenter.self="showTooltip"
        @mouseleave.self="hideTooltip"
        data-tooltip="<?= $escaper->escapeHtmlAttr(json_encode($toolTipData)) ?>"
    <?php endif; ?>
>
    <?php if ($swatchType === Swatch::SWATCH_TYPE_VISUAL_COLOR): ?>
        <span
            class="block size-full"
            style="background-color: <?= $escaper->escapeHtmlAttr($swatchData['value']) ?>"
        ></span>
    <?php elseif ($swatchType === Swatch::SWATCH_TYPE_VISUAL_IMAGE): ?>
        <img
            src="<?= $escaper->escapeUrl($swatchData['value']) ?>"
            alt="<?= $escaper->escapeHtmlAttr($optionLabel) ?>"
            width="20"
            height="20"
            class="size-full object-cover"
            loading="lazy"
        >
    <?php endif; ?>
    <span
        <?php if ($isVisual): ?>
            class="sr-only"
        <?php endif; ?>
    ><?= $escaper->escapeHtml($optionLabel) ?></span>
    <input
        id="<?= $escaper->escapeHtmlAttr($id) ?>"
        type="radio"
        name="super_attribute[<?= $escaper->escapeHtml($attributeId) ?>]"
        value="<?= $escaper->escapeHtml($optionId) ?>"
        @change="reflectOption"
        data-attribute-id="<?= $escaper->escapeHtmlAttr($attributeId) ?>"
        required
        class="sr-only"
    >
</label>
