<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\AbstractBlock;

/** @var AbstractBlock $sectionBlock */
/** @var Escaper $escaper */

?>

<?php if ($title = $sectionBlock->getTitle()): ?>
    <h2 class="mb-6 text-2xl text-center md:text-left">
        <?= $escaper->escapeHtml($title) ?>
    </h2>
<?php endif; ?>

