<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Edit $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>

<?php if ($product->isVisibleInSiteVisibility()) : ?>
    <a class="action edit btn btn-secondary inline-flex mr-2 p-2" href="<?= $block->escapeUrl($block->getItemConfigureUrl($item)) ?>">
        <svg fill="none" viewBox="0 0 24 24" stroke="currentColor" size="16" class="h-5 w-5">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z">

            </path>
        </svg>
        <span class="sr-only"><?= $block->escapeHtml(__('Edit')) ?></span>
    </a>
<?php endif ?>
