<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

?>

if (!this.hasCaptchaToken) {
    window.googleRecaptchaCallback = (token) => {
        $form['g-recaptcha-response'].value = token;
        this.errors = 0;
        this.hasCaptchaToken = 1;
        this.submitForm();
    }

    this.errors = 1;
    grecaptcha.execute();
}
